- hosts: localhost
  gather_facts: true
  connection: local
  tasks:
    - include_vars: '{{ ansible_os_family | lower }}.yml'

    - name: Create a directory for dependencies
      file:
        path: '{{ ansible_env.HOME }}/.cache/esearch-dev'
        state: directory

    - name: Setup global dependencies
      block:
        - name: packages
          package:
            name: '{{ item }}'
            state: present
          become: '{{ package_become }}'
          with_items:
            - luarocks
            - git
            - curl
            - ragel
            - unzip
            - neovim
            - '{{ vim_package_name }}'
            - '{{ tar_package_name }}'
            - '{{ pip_package_name }}'
            - '{{ ps_package_name }}'
        # - name: go
        #   unarchive:
        #     src: 'https://golang.org/dl/go1.11.linux-amd64.tar.gz'
        #     dest: '{{ ansible_env.HOME }}/.cache/esearch-dev'
        #     remote_src: true

        - name: lua linter
          command: luarocks install luacheck
          become: '{{ package_become }}'
          args:
            creates: /usr/local/bin/luacheck
        - name: pip packages
          pip:
            name: ['vim-vint', 'neovim']
            state: present

    - name: Setup greppers
      block:
        - name: from system package manager
          package:
            name: '{{ item }}'
            state: present
          become: '{{ package_become }}'
          with_items:
            - '{{ ag_package_name }}'
            - '{{ ack_package_name }}'
        - name: From PIP
          pip:
            name: ['semgrep']
            state: present
        - name: From go-get
          command: "go get {{ item }}"
          environment:
            GO111MODULE: "on"
          with_items:
            - mvdan.cc/gogrep
        - name: install prebuilt
          block:
            - name: download
              unarchive:
                src: '{{ item.download_url }}'
                dest: /tmp
                remote_src: true
              with_items: '{{ greppers }}'
            - name: find extracted binary
              find:
                paths: /tmp
                recurse: true
                patterns: '{{ item.bin }}'
              register: bins
              with_items: '{{ greppers }}'
            - name: copy into /usr/local/bin
              copy:
                src: '{{ item.path }}'
                dest: '/usr/local/bin/{{ item.path | basename }}'
              become: '{{ package_become }}'
              with_items: '{{ bins.results | map(attribute="files") | map("first") | list }}'
            - name: make executable
              file:
                dest: '/usr/local/bin/{{ item.bin }}'
                mode: a+x
              become: '{{ package_become }}'
              with_items: '{{ greppers }}'
          vars:
            - greppers:
              - {bin: pt, download_url: '{{ pt_download_url }}'}
              - {bin: rg, download_url: '{{ rg_download_url }}'}
        - name: configure git-grep
          block:
            - git_config: {scope: global, name: core.precomposeunicode, value: 'true'}
            - git_config: {scope: global, name: core.quotePath, value: 'false'}

    - name: setup plugin dependencies
      git:
        repo: "{{ item }}"
        dest: "~/.cache/esearch-dev/plugins/{{ item | urlsplit('path') | basename | splitext | first }}"
      with_items:
        - https://github.com/mg979/vim-visual-multi.git
        - https://github.com/tpope/vim-fugitive.git
        - https://github.com/preservim/nerdtree.git
        - https://github.com/justinmk/vim-dirvish.git
        - https://github.com/ipod825/vim-netranger.git
        - https://github.com/lambdalisue/fern.vim.git
        - https://github.com/Shougo/defx.nvim.git
        - https://github.com/roxma/nvim-yarp.git
        - https://github.com/roxma/vim-hug-neovim-rpc.git

    - name: setup testing dependencies
      block:
        - name: libs
          bundler:
            state: present
            extra_args: '--without development'
        - name: vader testing framework
          git:
            repo: https://github.com/junegunn/vader.vim.git
            dest: ~/.cache/esearch-dev/plugins/vader.vim
